---
- name: Deploy MERN App
  hosts: localhost
  vars:
    dockerhub_username: "{{ dockerhub_username }}"
    dockerhub_password: "{{ dockerhub_password }}"
  tasks:
    - name: Login to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Build React frontend image
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/fitness-frontend"
        tag: latest
        build:
          path: ./frontend

    - name: Push React frontend image
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/fitness-frontend"
        tag: latest
        push: yes

    - name: Build Node backend image
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/fitness-backend"
        tag: latest
        build:
          path: ./backend

    - name: Push Node backend image
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/fitness-backend"
        tag: latest
        push: yes
