- name: Deploy MERN App
  hosts: localhost
  tasks:
    - name: Login to Docker Hub
      command: docker login -u aditya14rudra -p Aaj+14docker

    - name: Build React frontend image
      command: docker build -t aditya14rudra/fitness-frontend:latest ./fron>
    - name: Build Node.js backend image
      command: docker build -t aditya14rudra/fitness-backend:latest ./backe>
    - name: Push frontend image
      command: docker push aditya14rudra/fitness-frontend:latest

    - name: Push backend image
      command: docker push aditya14rudra/fitness-backend:latest

    - name: Apply Kubernetes deployment
      command: kubectl apply -f k8s/
